<a href="https://colab.research.google.com/github/Neucielle/WoMakersCode/blob/main/Introdu%C3%A7%C3%A3o_ao_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
l = [1, 2, 3, 4]
arr1 = np.array(l)

In [3]:
arr1

array([1, 2, 3, 4])

In [5]:
np.zeros((3, 4)) # Tuplas -> 3 linhas e 4 colunas por exemplo

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

# Tipo de dados em um numpy array


In [ ]:
np.array([2.14, 6.25, 160.87, 8.4]).dtype

dtype('float64')

In [ ]:
np.array([2, 6, 160, 8]).dtype

dtype('int64')

In [ ]:
np.array(["Hello", "Coder", "Girls"]).dtype

dtype('<U5')

In [ ]:
arr_flaot32 = np.array([2.14, 6.25, 160.87], dtype=np.float32)
arr_flaot32

array([  2.14,   6.25, 160.87], dtype=float32)

In [ ]:
arr_vf = np.array([[True, False], [True, True]], dtype=np.bool8)
arr_vf.astype(np.int32)

array([[1, 0],
       [1, 1]], dtype=int32)

In [ ]:
np.array(["pedra", False , 42, 42.42])

array(['pedra', 'False', '42', '42.42'], dtype='<U32')

In [ ]:
np.array([0, 10]).dtype

dtype('int64')

In [ ]:
np.array([0, 10, 1.]).dtype

dtype('float64')

In [ ]:
np.array([True, False]).dtype

dtype('bool')

In [ ]:
np.array([True, False, 12]).dtype

dtype('int64')

In [8]:
arr_range = np.arange(1, 11)
arr_range

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
type(arr_range)

numpy.ndarray

In [11]:
np.random.random((1, 10))

array([[0.5877632 , 0.71111185, 0.9607809 , 0.98051793, 0.19063795,
        0.12895125, 0.61374537, 0.53056908, 0.5275606 , 0.43977731]])

###  1. Crie um array com 4 linhas e 3 colunas com valores aleatórios:

In [13]:
np.random.random((4, 3))

array([[0.80386475, 0.13266403, 0.97466022],
       [0.33212734, 0.37694546, 0.63994299],
       [0.66719645, 0.84577179, 0.07950538],
       [0.03447274, 0.57988135, 0.8547359 ]])

### 2. Crie um array com 5 colunas e 10 linhas inicializando no zero

In [14]:
np.zeros((10, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### 3. Crie um array com valores inteiros, 3 linhas e 5 colunas e com valores aleatórios.

In [15]:
np.random.randint(1, 100, (3, 5))

array([[47, 26,  3, 44, 72],
       [ 9, 83, 27, 31,  2],
       [97, 37, 16, 70, 11]])

## Array 3D


In [17]:
arr1_2d = np.array([[1, 2], [4, 5]])
arr2_2d = np.array([[7, 8], [10, 11]])
arra3_2d = np.array([[13, 14], [16, 17]])

arr1_3d = np.array([arr1_2d, arr2_2d, arra3_2d])
arr1_3d

array([[[ 1,  2],
        [ 4,  5]],

       [[ 7,  8],
        [10, 11]],

       [[13, 14],
        [16, 17]]])

In [19]:
np.zeros((3, 4, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])